sudo: required
services: 
  - docker

before_install:
  - docker build -t nb1333/docker-react --progress plain -f Dockerfile.dev .

script:
  - docker run -e CI=true nb1333/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "web-app"
  env: "Web-app-env"
  bucket_name: "elasticbeanstalk-us-east-1-475577011402"
  bocket_path: "web-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"